# Basic
encoding: utf-8
title: bot007
subtitle: Space of a researcher, developer and engineer
welcome_message: Welcome to my space.
description: 我的技术博客及随笔
creator: <a href="https://github.com/taobot007">@taobot007</a>

# url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# # The blog button should not be removed.
# blog_button:
#     title: All Blogs
#     # description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Homepage, description: all, url: '/'}
    - {title: All Blogs, description: all, url: '/archive'}
    - {title: Category, description: tags, url: '/tags'}
    # - {title: Message, description: messages, url: '/message'}
    # - {title: About me, description: about, url: '/about'}

# Pagination
plugins:
    - jekyll-paginate
    - jekyll-seo-tag

paginate: 10
paginate_path: "page/:num/"

# Comment
# comment:
#     disqus: vno-jekyll
#     # duoshuo:

# Social
social:
    # weibo: onevcat
    github: 545zhou
    twitter: 545zhou
    # gplus: 107108267983477358170
    mail: 545zhou@gmail.com

# Google Analytics
ga:
    id: UA-43166551-1
    host: my_blog

axn_tight_df = source_df.select([ c for c in ['country_cd', 'zip_5_cd', 'lst_5_pri_str_id', 'fst_3_str_nm', 'fst_2_unit_id', 'pos_4_5_str_nm', 'count_buids_per_key', 'buid')
axn_loose_new = axn_tight_df.dripDuplicates()
print("original anx_loose count")
print(axn_loose_new.count())